Drop references to sample-repo
rancher-sandbox/cos-toolkit-docs pull request #60
Opened 2021-11-17 10:13 UTC by Itxaka

Signed-off-by: Itxaka <igarcia@suse.com>

2021-11-17 10:15 UTC, Itxaka commented
Changed some example to the epinio sample which probably requires being deprecated also? Or we can keep it?
Changed some refs to the c3os repo, which probably would be the one to serve as repo.

Maybe we could change some references to cloudOs by Darren?

2021-11-22 08:51 UTC, mudler commented on content/en/docs/Customizing/login.md
>  - [Example accounting file](https://github.com/rancher-sandbox/epinio-appliance-demo-sample/blob/master/packages/epinioOS/04_accounting.yaml)
The epinio one is archived too, so this needs to be dropped as well

2021-11-22 08:52 UTC, mudler commented on content/en/docs/Development/creating_derivatives.md
>  ## Additional packages
This section below should be removed as well, It's still refering to the sample repositories

2021-11-22 08:52 UTC, mudler commented on content/en/docs/Reference/_index.md
>  - [EpinioOS sample repository](https://github.com/rancher-sandbox/epinio-appliance-demo-sample)
Same here, the epinio appliance is archived as well

2021-11-22 08:52 UTC, mudler commented on content/en/docs/Reference/high_level_architecture.md
> +The developer of the derivative applies a customization layer during build, which is an augmentation layer in the same form of `cos-toolkit` itself. [An example repository is provided](https://github
Another reference to the epinio one

2021-11-22 08:53 UTC, mudler commented on content/en/docs/Reference/selinux.md
> +You can use the [epinio sample](https://github.com/rancher-sandbox/epinio-appliance-demo-sample/tree/master/packages/selinux-policies) policy as a kickstart to customize on top.
This should be removed as well. maybe embed the policies example directly here?

2021-11-22 08:54 UTC, mudler commented on content/en/docs/Creating derivatives/build_iso.md
> +{{<githubembed repo="mudler/c3os" file="iso.yaml" lang="yaml">}}
maybe we should provide an iso.yaml example file inside cos-toolkit `example` dir

2021-11-22 08:55 UTC, mudler requested changes
Just few nits, mainly because there are still references to the epinio appliance which is archived too

2021-11-30 09:34 UTC, Itxaka commented
redy to re-review @mudler

2021-11-30 11:29 UTC, mudler commented on content/en/docs/Customizing/upgrades.md
> -An example on how to tweak this file via cloud-init is available [here](https://github.com/rancher-sandbox/cos-toolkit-sample-repo/blob/7355876847367b75485873987e1217f1e1fe6254/packages/sampleOS/02_u
We can link directly to the cOS ones here https://github.com/rancher-sandbox/cOS-toolkit/blob/master/packages/cloud-config/oem/02_upgrades.yaml

2021-11-30 11:29 UTC, mudler commented on content/en/docs/Customizing/upgrades.md
> -An example on how to tweak this file via cloud-init is available [here](https://github.com/rancher-sandbox/cos-toolkit-sample-repo/blob/7355876847367b75485873987e1217f1e1fe6254/packages/sampleOS/02_u
ah. was already linked above, nevermind!

2021-11-30 11:30 UTC, mudler approved these changes

2021-12-01 10:18 UTC, merged