Include elemental commands instead of the cos-* variants
rancher-sandbox/cos-toolkit-docs pull request #70
Opened 2022-03-02 11:44 UTC by davidcassany

Signed-off-by: David Cassany <dcassany@suse.com>

2022-03-02 16:39 UTC, davidcassany commented
Related to rancher-sandbox/cOS-toolkit#1144

2022-03-02 16:42 UTC, Itxaka requested changes

2022-03-02 16:42 UTC, Itxaka commented on content/en/docs/Getting started/upgrading.md
> +  name: elemetal-upgrade
Typo

2022-03-02 17:12 UTC, davidcassany commented on content/en/docs/Getting started/upgrading.md
> +  name: elemetal-upgrade
ouch...

2022-03-03 10:13 UTC, mudler commented
Maybe since `cosign` changed to be disabled by default, we should mention it in the cosign docs section? https://github.com/rancher-sandbox/cos-toolkit-docs/blob/master/content/en/docs/Creating%20derivatives/cosign.md

2022-03-03 10:26 UTC, davidcassany commented
> EDIT: maybe that's not the best place, but it is worth to mention how to enable it during upgrades/install etc.

Yes, that's why I did not include it here. This PR is not adding any new docs just adapting to the current commands. I am working in another PR to add few little things, I can do it there.

2022-03-03 14:31 UTC, davidcassany commented
@mudler at the end I did not create another PR, it wasn't that much.

2022-03-03 15:12 UTC, Itxaka reviewed
nice!

2022-03-03 15:12 UTC, Itxaka approved these changes

2022-03-04 08:45 UTC, mudler approved these changes

2022-03-04 10:33 UTC, merged